### ISSUE TITLE
Upstream Java t-digest has some important changes

### ISSUE THREAD

**Issue by tdunning** [beyondeye/tdigest_kotlin_multiplatform#1]
I found some insidious bugs related to repeated counts. You may want to check out recent changes to the Java code to see if they affect your code.

Please also check that the java distro references and credits your work sufficiently.

**Comment by beyondeye** [comment]
thanks. I have actually integrated all recent changes from the main java distro, but did not commit them yet. I will soon, and also create a pull request for reference this port in the java repository readme

**Comment by tdunning** [comment]
That was quick given I only put the changes to the sort in yesterday.

Well done to respond that fast!

**Comment by beyondeye** [comment]
all changes merged, including tests. I have also created a pull request in your repository for adding a link to the kotlin implementation. thanks again to letting me know about the changes

**Comment by tdunning** [comment]
cool.

That was quick!
